<a href="https://colab.research.google.com/github/Anshulmohan27/Python_Everything/blob/main/Pandas_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nafiulislam490/bank-transaction-fraud-detection-dataset")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/nafiulislam490/bank-transaction-fraud-detection-dataset/1.archive...

100%|██████████| 42.4M/42.4M [00:00<00:00, 163MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/nafiulislam490/bank-transaction-fraud-detection-dataset/versions/1

In [22]:
import pandas as pd
import os
print("files in the directory")
for file in os.listdir(path):
  print(file)

df = pd.read_csv(os.path.join(path,'bank_fraud.csv'))
df.head()

files in the directory
bank_fraud.csv

,transaction_id,customer_id,transaction_date,transaction_time,hour_of_day,is_weekend,is_night_transaction,country,city,merchant_category,...,transaction_amount,num_prev_transactions,transaction_freq_monthly,distance_from_home_km,time_since_last_txn_hrs,is_international,failed_attempts,pin_changed_recently,is_fraud,fraud_type
0,TXN0000000001,CUST00121959,2023-08-17,21:13:00,21,0,0,USA,London,Grocery,...,39.49,157,23,52.7,10.20,0,0,0,0,NaN
1,TXN0000000002,CUST00146868,2024-02-06,05:16:00,5,0,1,UK,New York,Healthcare,...,153.71,153,23,0.9,12.47,0,0,0,0,NaN
2,TXN0000000003,CUST00131933,2024-06-28,12:15:00,12,0,0,Canada,Delhi,Grocery,...,118.20,161,20,9.2,0.08,0,1,0,0,NaN
3,TXN0000000004,CUST00103695,2023-03-16,02:53:00,2,0,1,France,Tokyo,Utilities,...,49.50,160,25,14.8,17.94,1,0,1,1,Synthetic Identity
4,TXN0000000005,CUST00119880,2024-07-12,12:39:00,12,0,0,Canada,Melbourne,Clothing,...,30.74,134,18,38.9,2.16,0,0,0,0,NaN

In [7]:
df.shape[0] #number of rows

1000000

In [8]:
df.shape[1] #number of columns

26

In [9]:
df.columns #names of columns

Index(['transaction_id', 'customer_id', 'transaction_date', 'transaction_time',
       'hour_of_day', 'is_weekend', 'is_night_transaction', 'country', 'city',
       'merchant_category', 'payment_method', 'device_type', 'customer_age',
       'credit_score', 'account_age_years', 'account_balance',
       'transaction_amount', 'num_prev_transactions',
       'transaction_freq_monthly', 'distance_from_home_km',
       'time_since_last_txn_hrs', 'is_international', 'failed_attempts',
       'pin_changed_recently', 'is_fraud', 'fraud_type'],
      dtype='object')

In [23]:
df.info

<bound method DataFrame.info of        transaction_id   customer_id transaction_date transaction_time  \
0       TXN0000000001  CUST00121959       2023-08-17         21:13:00
1       TXN0000000002  CUST00146868       2024-02-06         05:16:00
2       TXN0000000003  CUST00131933       2024-06-28         12:15:00
3       TXN0000000004  CUST00103695       2023-03-16         02:53:00
4       TXN0000000005  CUST00119880       2024-07-12         12:39:00
...               ...           ...              ...              ...
999995  TXN0000999996  CUST00176672       2022-11-18         21:15:00
999996  TXN0000999997  CUST00005742       2021-07-03         22:57:00
999997  TXN0000999998  CUST00108137       2021-08-12         07:37:00
999998  TXN0000999999  CUST00117141       2021-06-07         07:09:00
999999  TXN0001000000  CUST00117401       2021-01-07         18:43:00

        hour_of_day  is_weekend  is_night_transaction country        city  \
0                21           0                     0     USA      London
1                 5           0                     1      UK    New York
2                12           0                     0  Canada       Delhi
3                 2           0                     1  France       Tokyo
4                12           0                     0  Canada   Melbourne
...             ...         ...                   ...     ...         ...
999995           21           0                     0  Mexico        Lyon
999996           22           1                     1  Mexico       Tokyo
999997            7           0                     0     USA  Manchester
999998            7           0                     0   Japan   São Paulo
999999           18           0                     0   India      Berlin

       merchant_category  ... transaction_amount num_prev_transactions  \
0                Grocery  ...              39.49                   157
1             Healthcare  ...             153.71                   153
2                Grocery  ...             118.20                   161
3              Utilities  ...              49.50                   160
4               Clothing  ...              30.74                   134
...                  ...  ...                ...                   ...
999995       Electronics  ...            1923.52                   145
999996   Online Shopping  ...             146.16                   154
999997           Grocery  ...              27.38                   148
999998       Electronics  ...             365.30                   150
999999   Crypto Exchange  ...              60.82                   154

        transaction_freq_monthly  distance_from_home_km  \
0                             23                   52.7
1                             23                    0.9
2                             20                    9.2
3                             25                   14.8
4                             18                   38.9
...                          ...                    ...
999995                        20                   36.5
999996                        17                   20.0
999997                        20                    3.4
999998                        16                   63.1
999999                        15                   12.6

        time_since_last_txn_hrs  is_international  failed_attempts  \
0                         10.20                 0                0
1                         12.47                 0                0
2                          0.08                 0                1
3                         17.94                 1                0
4                          2.16                 0                0
...                         ...               ...              ...
999995                     1.58                 0                0
999996                     2.10                 0                0
999997                     2.74                 0                1
999998                     3.71                 1                1
999999                    13.53                 1                0

        pin_changed_recently  is_fraud          fraud_type
0                          0         0                 NaN
1                          0         0                 NaN
2                          0         0                 NaN
3                          1         1  Synthetic Identity
4                          0         0                 NaN
...                      ...       ...                 ...
999995                     0         0                 NaN
999996                     0         0                 NaN
999997                     0         0                 NaN
999998                     0         0                 NaN
999999                     0         0                 NaN

[1000000 rows x 26 columns]>

In [24]:
df.isna().sum() #missing values

transaction_id                   0
customer_id                      0
transaction_date                 0
transaction_time                 0
hour_of_day                      0
is_weekend                       0
is_night_transaction             0
country                          0
city                             0
merchant_category                0
payment_method                   0
device_type                      0
customer_age                     0
credit_score                     0
account_age_years                0
account_balance                  0
transaction_amount               0
num_prev_transactions            0
transaction_freq_monthly         0
distance_from_home_km            0
time_since_last_txn_hrs          0
is_international                 0
failed_attempts                  0
pin_changed_recently             0
is_fraud                         0
fraud_type                  944745
dtype: int64

In [26]:
df.isna().sum()*100/df.shape[0] #percentage of missing values in each column

transaction_id               0.0000
customer_id                  0.0000
transaction_date             0.0000
transaction_time             0.0000
hour_of_day                  0.0000
is_weekend                   0.0000
is_night_transaction         0.0000
country                      0.0000
city                         0.0000
merchant_category            0.0000
payment_method               0.0000
device_type                  0.0000
customer_age                 0.0000
credit_score                 0.0000
account_age_years            0.0000
account_balance              0.0000
transaction_amount           0.0000
num_prev_transactions        0.0000
transaction_freq_monthly     0.0000
distance_from_home_km        0.0000
time_since_last_txn_hrs      0.0000
is_international             0.0000
failed_attempts              0.0000
pin_changed_recently         0.0000
is_fraud                     0.0000
fraud_type                  94.4745
dtype: float64

In [35]:
df['customer_id'].nunique() #number of unique customers.

198662

In [36]:
df['merchant_category'].nunique() #number of unique merchants.

15

In [38]:
print(df["transaction_amount"].mean()) #average transaction amount

204.72466542

In [39]:
df[df.transaction_amount > 10000] #transaciton amount > 10000

,transaction_id,customer_id,transaction_date,transaction_time,hour_of_day,is_weekend,is_night_transaction,country,city,merchant_category,...,transaction_amount,num_prev_transactions,transaction_freq_monthly,distance_from_home_km,time_since_last_txn_hrs,is_international,failed_attempts,pin_changed_recently,is_fraud,fraud_type
19732,TXN0000019733,CUST00199396,2021-11-11,18:40:00,18,0,0,Brazil,New York,Electronics,...,13851.98,134,20,5.7,2.68,0,0,0,0,NaN
25018,TXN0000025019,CUST00142077,2020-09-06,10:08:00,10,1,0,USA,Sydney,Electronics,...,32014.83,146,18,22.4,1.74,0,1,0,0,NaN
28445,TXN0000028446,CUST00002992,2023-12-22,12:58:00,12,0,0,UK,Guadalajara,Electronics,...,15092.80,161,20,42.2,13.23,0,0,0,0,NaN
33782,TXN0000033783,CUST00026229,2023-09-16,18:33:00,18,1,0,Brazil,Manchester,Electronics,...,12346.67,164,19,6.9,5.77,0,2,0,0,NaN
38970,TXN0000038971,CUST00116961,2022-10-29,14:16:00,14,1,0,India,Lyon,Electronics,...,11928.65,156,11,8.0,72.23,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
936470,TXN0000936471,CUST00029373,2023-03-04,15:23:00,15,1,0,Australia,New York,Jewelry,...,10129.94,130,19,9.2,1.39,0,0,0,0,NaN
983375,TXN0000983376,CUST00108905,2024-02-11,00:13:00,0,1,1,USA,Los Angeles,Jewelry,...,15643.52,159,8,38.3,10.83,0,4,0,0,NaN
983440,TXN0000983441,CUST00182896,2022-05-11,03:29:00,3,0,1,USA,Mumbai,Travel,...,11039.47,156,16,65.1,5.43,1,0,0,0,NaN
985944,TXN0000985945,CUST00091880,2021-03-19,03:11:00,3,0,1,Canada,Tokyo,Jewelry,...,12277.73,133,20,8.3,1.64,0,1,0,0,NaN
995789,TXN0000995790,CUST00106746,2023-12-19,23:42:00,23,0,1,Mexico,Sydney,Jewelry,...,11863.04,165,20,14.1,9.71,0,0,0,0,NaN

In [42]:
df.columns

Index(['transaction_id', 'customer_id', 'transaction_date', 'transaction_time',
       'hour_of_day', 'is_weekend', 'is_night_transaction', 'country', 'city',
       'merchant_category', 'payment_method', 'device_type', 'customer_age',
       'credit_score', 'account_age_years', 'account_balance',
       'transaction_amount', 'num_prev_transactions',
       'transaction_freq_monthly', 'distance_from_home_km',
       'time_since_last_txn_hrs', 'is_international', 'failed_attempts',
       'pin_changed_recently', 'is_fraud', 'fraud_type'],
      dtype='object')

In [44]:
df[df['is_fraud']==1]

,transaction_id,customer_id,transaction_date,transaction_time,hour_of_day,is_weekend,is_night_transaction,country,city,merchant_category,...,transaction_amount,num_prev_transactions,transaction_freq_monthly,distance_from_home_km,time_since_last_txn_hrs,is_international,failed_attempts,pin_changed_recently,is_fraud,fraud_type
3,TXN0000000004,CUST00103695,2023-03-16,02:53:00,2,0,1,France,Tokyo,Utilities,...,49.50,160,25,14.8,17.94,1,0,1,1,Synthetic Identity
5,TXN0000000006,CUST00110269,2024-06-26,04:28:00,4,0,1,Canada,Guadalajara,Crypto Exchange,...,35.36,157,19,23.0,31.46,0,2,0,1,Friendly Fraud
27,TXN0000000028,CUST00159766,2021-06-09,02:31:00,2,0,1,Japan,São Paulo,Crypto Exchange,...,26.33,136,26,0.9,1.23,1,5,0,1,Synthetic Identity
63,TXN0000000064,CUST00110511,2022-03-10,04:58:00,4,0,1,Brazil,Los Angeles,Travel,...,101.78,148,13,3.5,1.92,0,0,0,1,Identity Theft
72,TXN0000000073,CUST00171830,2024-08-18,09:43:00,9,1,0,Mexico,New York,Education,...,124.81,149,9,88.6,1.72,0,2,0,1,Account Takeover
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999827,TXN0000999828,CUST00090518,2023-11-20,13:05:00,13,0,0,Mexico,Rio,Travel,...,337.65,157,18,1.5,3.20,1,0,0,1,Friendly Fraud
999917,TXN0000999918,CUST00164413,2020-04-19,03:02:00,3,1,1,Canada,Lyon,Fuel,...,37.55,135,18,10.6,9.56,1,0,0,1,Friendly Fraud
999939,TXN0000999940,CUST00030293,2022-09-14,06:34:00,6,0,1,Canada,Rio,Entertainment,...,96.17,150,28,28.7,19.21,0,0,0,1,Friendly Fraud
999965,TXN0000999966,CUST00142439,2020-10-13,16:35:00,16,0,0,Japan,Tokyo,Education,...,73.46,129,23,8.1,5.67,0,1,0,1,Identity Theft
999966,TXN0000999967,CUST00025105,2022-12-25,21:37:00,21,1,0,Australia,Tokyo,Entertainment,...,14.74,157,25,40.6,22.76,0,0,0,1,Friendly Fraud

In [50]:
df[
    (df["is_fraud"] == 1) & (df["transaction_amount"]>50000)
]

Empty DataFrame
Columns: [transaction_id, customer_id, transaction_date, transaction_time, hour_of_day, is_weekend, is_night_transaction, country, city, merchant_category, payment_method, device_type, customer_age, credit_score, account_age_years, account_balance, transaction_amount, num_prev_transactions, transaction_freq_monthly, distance_from_home_km, time_since_last_txn_hrs, is_international, failed_attempts, pin_changed_recently, is_fraud, fraud_type]
Index: []

[0 rows x 26 columns]

In [61]:
df["transaction_amount"].nlargest(20) #largest 20

751939    46129.60
25018     32014.83
83851     30659.38
178932    27161.16
202966    25378.71
79373     21570.37
593918    19209.70
185982    17720.38
721776    17708.44
798138    17441.28
813166    17347.99
256140    16775.40
58000     16657.44
750827    16147.88
493004    15749.48
892318    15739.68
983375    15643.52
122173    15474.76
216252    15278.12
707145    15210.30
Name: transaction_amount, dtype: float64

In [62]:
df["transaction_amount"].nsmallest(20)

23573     1.0
30054     1.0
118930    1.0
130310    1.0
181710    1.0
199532    1.0
226741    1.0
244803    1.0
249718    1.0
259214    1.0
266451    1.0
355352    1.0
358549    1.0
396276    1.0
512955    1.0
515778    1.0
577086    1.0
589733    1.0
612862    1.0
634454    1.0
Name: transaction_amount, dtype: float64

In [68]:
fraud_list = df[df["is_fraud"]==1]
fraud_list.loc[fraud_list["transaction_amount"].idxmax()] # largest fraud transaction

transaction_id               TXN0000468116
customer_id                   CUST00122111
transaction_date                2022-07-26
transaction_time                  17:19:00
hour_of_day                             17
is_weekend                               0
is_night_transaction                     0
country                             France
city                                London
merchant_category                  Jewelry
payment_method                 Credit Card
device_type                         Mobile
customer_age                            49
credit_score                           716
account_age_years                      2.1
account_balance                   10239.69
transaction_amount                14767.61
num_prev_transactions                  156
transaction_freq_monthly                16
distance_from_home_km                  1.6
time_since_last_txn_hrs              69.02
is_international                         0
failed_attempts                          3
pin_changed_recently                     1
is_fraud                                 1
fraud_type                  Identity Theft
Name: 468115, dtype: object

In [72]:
df.groupby("customer_id").size() #number of transactions per customer

customer_id
CUST00000001    4
CUST00000002    4
CUST00000003    3
CUST00000004    6
CUST00000005    5
               ..
CUST00199995    7
CUST00199996    9
CUST00199997    1
CUST00199998    8
CUST00199999    3
Length: 198662, dtype: int64

In [75]:
df.groupby("customer_id").size().idxmax()
df["customer_id"].value_counts().head(1) #customer with most transations

customer_id
CUST00165481    19
Name: count, dtype: int64

In [76]:
df.groupby("customer_id")["transaction_amount"].sum() #total transaciton amount per customer

customer_id
CUST00000001    1116.68
CUST00000002     481.84
CUST00000003     706.06
CUST00000004    1495.38
CUST00000005     853.20
                 ...
CUST00199995     505.58
CUST00199996     733.42
CUST00199997     135.77
CUST00199998     788.84
CUST00199999      78.83
Name: transaction_amount, Length: 198662, dtype: float64

In [77]:
df.groupby("customer_id")["transaction_amount"].mean() #average trasaction amount per customer

customer_id
CUST00000001    279.170000
CUST00000002    120.460000
CUST00000003    235.353333
CUST00000004    249.230000
CUST00000005    170.640000
                   ...
CUST00199995     72.225714
CUST00199996     81.491111
CUST00199997    135.770000
CUST00199998     98.605000
CUST00199999     26.276667
Name: transaction_amount, Length: 198662, dtype: float64

In [78]:
df.columns

Index(['transaction_id', 'customer_id', 'transaction_date', 'transaction_time',
       'hour_of_day', 'is_weekend', 'is_night_transaction', 'country', 'city',
       'merchant_category', 'payment_method', 'device_type', 'customer_age',
       'credit_score', 'account_age_years', 'account_balance',
       'transaction_amount', 'num_prev_transactions',
       'transaction_freq_monthly', 'distance_from_home_km',
       'time_since_last_txn_hrs', 'is_international', 'failed_attempts',
       'pin_changed_recently', 'is_fraud', 'fraud_type'],
      dtype='object')

In [81]:
df["transaction_amount"].agg(
    ["mean", "median", "min", "max"]
)

mean        204.724665
median       73.120000
min           1.000000
max       46129.600000
Name: transaction_amount, dtype: float64

In [83]:
df.groupby("merchant_category")['transaction_amount'].sum()

merchant_category
ATM Withdrawal      5957047.81
Clothing            6036162.51
Crypto Exchange     6014716.27
Education           6024239.32
Electronics        44524739.65
Entertainment       5985847.33
Fuel                6022694.78
Gaming              5949927.88
Grocery             5974231.14
Healthcare          6052937.55
Jewelry            43935478.76
Online Shopping     6004227.79
Restaurant          6031942.99
Travel             44145743.98
Utilities           6064727.66
Name: transaction_amount, dtype: float64

In [85]:
df.groupby("merchant_category")['transaction_amount'].sum().idxmax()

'Electronics'

In [88]:
average_transaction = df['transaction_amount'].mean()
print(average_transaction)
df[df["transaction_amount"]>average_transaction]

204.72466542

,transaction_id,customer_id,transaction_date,transaction_time,hour_of_day,is_weekend,is_night_transaction,country,city,merchant_category,...,transaction_amount,num_prev_transactions,transaction_freq_monthly,distance_from_home_km,time_since_last_txn_hrs,is_international,failed_attempts,pin_changed_recently,is_fraud,fraud_type
8,TXN0000000009,CUST00168267,2021-12-07,03:23:00,3,0,1,USA,Melbourne,Online Shopping,...,330.47,164,23,27.8,47.27,0,0,0,0,NaN
10,TXN0000000011,CUST00112728,2020-03-05,03:16:00,3,0,1,USA,London,Clothing,...,229.42,166,23,16.9,1.34,0,0,0,0,NaN
19,TXN0000000020,CUST00059736,2022-12-06,08:54:00,8,0,0,USA,Osaka,Clothing,...,218.76,139,20,46.4,23.58,0,2,0,0,NaN
21,TXN0000000022,CUST00064926,2024-09-13,17:57:00,17,0,0,Mexico,New York,ATM Withdrawal,...,280.27,115,27,9.5,12.80,0,0,0,0,NaN
34,TXN0000000035,CUST00002748,2021-03-30,16:19:00,16,0,0,India,London,Travel,...,824.35,134,30,34.1,15.96,1,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999983,TXN0000999984,CUST00100104,2023-04-02,21:14:00,21,1,0,India,Osaka,Jewelry,...,297.30,142,23,52.4,5.02,0,0,0,0,NaN
999985,TXN0000999986,CUST00025835,2022-01-08,21:52:00,21,1,0,Japan,Berlin,Crypto Exchange,...,279.53,143,20,18.0,5.85,0,0,0,0,NaN
999993,TXN0000999994,CUST00186720,2023-08-15,07:12:00,7,0,0,Mexico,Los Angeles,Jewelry,...,524.24,145,22,32.6,15.00,1,0,0,0,NaN
999995,TXN0000999996,CUST00176672,2022-11-18,21:15:00,21,0,0,Mexico,Lyon,Electronics,...,1923.52,145,20,36.5,1.58,0,0,0,0,NaN
999998,TXN0000999999,CUST00117141,2021-06-07,07:09:00,7,0,0,Japan,São Paulo,Electronics,...,365.30,150,16,63.1,3.71,1,1,0,0,NaN

In [95]:
df["customer_average"] = (df.groupby("customer_id")["transaction_amount"].transform('mean'))

In [97]:
df["amount_diff"]=(df["transaction_amount"]-df["customer_average"])
df["amount_diff"]

0         -198.965000
1           -4.746000
2           -2.763333
3           -2.890000
4          -52.722000
             ...
999995    1242.753333
999996      86.248571
999997    -265.560000
999998     189.307500
999999      18.842000
Name: amount_diff, Length: 1000000, dtype: float64

In [90]:
df.groupby("customer_id")["is_fraud"].apply(lambda x: x==1)

customer_id
CUST00000001  321957     True
              355233    False
              566429    False
              681259    False
CUST00000002  188173    False
                        ...
CUST00199998  663109    False
              686974    False
CUST00199999  526419    False
              749014    False
              951320    False
Name: is_fraud, Length: 1000000, dtype: bool